version: "2.3"
services: 
  react:
    container_name: reab-pc-react
    build: ./reb-pc-react
    ports: [3000:3000]
  laravel:
    container_name: reab-pc-laravel
    build: ./web_api
    ports: [8000:8000]
    links: [db]
  db:
    container_name: reab-pc-mysql
    image: mysql
    expose: [3306]
    ports: [3306:3306]
    volumes: [/var/lib/mysql]
    environment:
      MYSQL_DATABASE: chatcha_db
      MYSQL_ROOT_PASSWORD: chatcha

